name: "GitHub to JIRA integration"
decription: "Minimalistic JIRA integration for GitHub"
author: "Vladan Paunovic"

inputs:
  GITHUB_TOKEN:
    decription: "GitHub token"
    required: true
  ON_LABEL:
    decription: "GitHub label"
    required: true
  JIRA_ISSUE_NAME:
    decription: "JIRA issue name (Story, Task)"
    required: true
  JIRA_API_HOST:
    decription: "JIRA API host"
    required: true
  JIRA_API_TOKEN:
    decription: "JIRA API token"
    required: true
  JIRA_EMAIL:
    decription: "JIRA user e-mail"
    required: true
  JIRA_PROJECT_ID:
    decription: "JIRA project ID"
    required: true
  after-jira-issue-message:
    description: "Comment message used to be commented on the issue after the issue is created in JIRA"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
