name: Test

on:
  issues:
    types: [labeled]

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
