name: Test

on:
  issues:
    types: [labeled]

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          JIRA_API_HOST: ${{secrets.JIRA_API_HOST}}
          JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}
          JIRA_EMAIL: ${{secrets.JIRA_EMAIL}}
          JIRA_PROJECT_ID: WTEST
          JIRA_ISSUE_NAME: Story
          after-jira-issue-message: |-
            We are prioritizing this issue in our development worklog
